### ISSUE TITLE
居然在这里看到了DS的计算方法

### ISSUE THREAD

**Issue by huiyadanli** [Womsxd/YuanShen_User_Info#1]
我以前写了一个这个角色信息查询的前端页面，后端也利用了这个接口，当时还没有做鉴权

然后作死发NGA后被秒封。

项目地址：https://github.com/babalae/genshin-info

最近有时间又抓包看了下，发现有个DS的请求头。没找到它的生成方法，居然在这里找到的。

我可以使用这段代码吗？会注明来源，希望mhy不要再和谐了:joy:

```python
def DSGet():
    mhyVersion = "2.1.0"
    n = md5(mhyVersion)
    i = str(int(time.time()))
    r = ''.join(random.sample(string.ascii_lowercase + string.digits, 6))
    c = md5("salt=" + n + "&t="+ i + "&r=" + r)
    return i + "," + r + "," + c
```

**Comment by Steesha** [comment]
啊这

**Comment by Loyisa** [comment]
我靠恁娘 你就是让接口被封的罪魁祸首?

**Comment by Makethingsy** [comment]
呃呃气死我了

**Comment by AHpxChina** [comment]
qswl！

**Comment by Womsxd** [comment]
可以(
不过不建议大范围公开宣传(这玩意还是私下用用好丶

**Comment by huiyadanli** [comment]
> 我靠恁娘 你就是让接口被封的罪魁祸首?

没错就是我，可是我也不知道也有别人在用。。。

**Comment by Admirepowered** [comment]
> > 我靠恁娘 你就是让接口被封的罪魁祸首?
> 
> 没错就是我，可是我也不知道也有别人在用。。。

**好家伙**大范围传播大家都没得用

**Comment by huiyadanli** [comment]
好了好了，我错了 😭

原先被封的主要原因应该是：
1. 接口无鉴权
2. 接口能够查到米游社未同步的账号（重点）

现在低调使用应该没事，反正我是不会去主动宣传了。

我这边页面用的后端，大概就是用了腾讯云的云函数简单做了个反代，有需要可以随意使用（F12自取，参数只需要UID）

@Womsxd @Steesha 大佬🐂🍺

**Comment by ColorfulGhost** [comment]
关于DS算法Java版本~
```
import cn.hutool.core.util.NumberUtil;
import cn.hutool.core.util.RandomUtil;
import cn.hutool.crypto.digest.MD5;
import cn.hutool.http.HttpRequest;
import cn.hutool.http.HttpResponse;
import cn.hutool.http.HttpUtil;

    String DSGet() {
        String mhyVersion = "2.1.0";
        String randomStr = "abcdefghijklmnopqrstuvwxyz0123456789";
        String n = MD5.create().digestHex(mhyVersion);
        String i = NumberUtil.roundStr(System.currentTimeMillis() / 1000.0,0);

        String r = "";
        for (int i1 = 0; i1 < 6; i1++) {
            r += Character.toString(RandomUtil.randomChar(randomStr));
        }
        String c = MD5.create().digestHex("salt=" + n + "&t=" + i + "&r=" + r);
        return i + "," + r + "," + c;
    }
```

**Comment by DreamsLing** [comment]
> 关于DS算法Java版本~
> 
> ```
> import cn.hutool.core.util.NumberUtil;
> import cn.hutool.core.util.RandomUtil;
> import cn.hutool.crypto.digest.MD5;
> import cn.hutool.http.HttpRequest;
> import cn.hutool.http.HttpResponse;
> import cn.hutool.http.HttpUtil;
> 
>     String DSGet() {
>         String mhyVersion = "2.1.0";
>         String randomStr = "abcdefghijklmnopqrstuvwxyz0123456789";
>         String n = MD5.create().digestHex(mhyVersion);
>         String i = NumberUtil.roundStr(System.currentTimeMillis() / 1000.0,0);
> 
>         String r = "";
>         for (int i1 = 0; i1 < 6; i1++) {
>             r += Character.toString(RandomUtil.randomChar(randomStr));
>         }
>         String c = MD5.create().digestHex("salt=" + n + "&t=" + i + "&r=" + r);
>         return i + "," + r + ",

> 关于DS算法Java版本~
> 
> ```
> import cn.hutool.core.util.NumberUtil;
> import cn.hutool.core.util.RandomUtil;
> import cn.hutool.crypto.digest.MD5;
> import cn.hutool.http.HttpRequest;
> import cn.hutool.http.HttpResponse;
> import cn.hutool.http.HttpUtil;
> 
>     String DSGet() {
>         String mhyVersion = "2.1.0";
>         String randomStr = "abcdefghijklmnopqrstuvwxyz0123456789";
>         String n = MD5.create().digestHex(mhyVersion);
>         String i = NumberUtil.roundStr(System.currentTimeMillis() / 1000.0,0);
> 
>         String r = "";
>         for (int i1 = 0; i1 < 6; i1++) {
>             r += Character.toString(RandomUtil.randomChar(randomStr));
>         }
>         String c = MD5.create().digestHex("salt=" + n + "&t=" + i + "&r=" + r);
>         return i + "," + r + "," + c;
>     }
> ```

能发下php写法嘛。。。我不会

**Comment by SinoAHpx** [comment]
> 能发下php写法嘛。。。我不会

要我开宝宝巴士教你写吗？
