### ISSUE TITLE
感觉作为一个账号信息查询脚本不返回账号名称，等级什么的有点奇怪

### ISSUE THREAD

**Issue by Jerry-FaGe** [Womsxd/YuanShen_User_Info#10]
大佬您好！最近在改进的一个bot用到了您的脚本[XiaoMiku01/PaimonBot](https://github.com/XiaoMiku01/PaimonBot/tree/main/src/plugins/mys)
这个bot会通过uid自动生成一张图片发送到QQ，我看了下源码发现已经留了显示等级头像的位置（如图左右上角）但是被注掉了
![image](https://user-images.githubusercontent.com/40235071/121151213-c020c000-c876-11eb-8e15-40d9befefb41.png)

看了下米忽悠的那个接口确实没有返回昵称等级什么的信息（太怪了，貌似米游社显示那一页的信息要调好几个不同的接口？）
大佬方便的话能否加入返回账号昵称等级之类的功能呢
如果不方便的话可否提供下对应的接口，我自己解析，谢谢啦

**Comment by Chika99** [comment]
您好，我对您的这个项目很感兴趣。调用的接口以及格式如下，其中avatars_list是包含角色id(int)的列表，headers不变。这个会返回角色的名称命座武器圣遗物等信息，正在打算参考您的项目，将其中显示前n个角色信息改为全部角色以及武器精炼命座等的显示
```
data = {"character_ids": avatars_list, "role_id": Uid, "server": ServerID}
url = "https://api-takumi.mihoyo.com/game_record/genshin/api/character"
```

**Comment by Jerry-FaGe** [comment]
> 您好，我对您的这个项目很感兴趣。调用的接口以及格式如下，其中avatars_list是包含角色id(int)的列表，headers不变。这个会返回角色的名称命座武器圣遗物等信息，正在打算参考您的项目，将其中显示前n个角色信息改为全部角色以及武器精炼命座等的显示
> 
> ```
> data = {"character_ids": avatars_list, "role_id": Uid, "server": ServerID}
> url = "https://api-takumi.mihoyo.com/game_record/genshin/api/character"
> ```

首先谢谢啦，不过我的需求可能表述的不太清晰，我说的头像等级昵称指的是这个`账号`的信息不是角色的。也就相当于图片左右上角所需要的数据，左上角那个流哈喇子的派蒙我想换成这个米游社账号的头像，右上角的XX我想换成这个原神账号的等级和世界等级，然后如果能获取帐号昵称（比如`100131271`这个Uid的游戏昵称叫`许多舰长`）的话，可能会在上面中心的框框内加一行来显示XD

**Comment by Chika99** [comment]
原神游戏等级以及游戏昵称可以通过`https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn`获取，米游社头像`https://bbs-api.mihoyo.com/user/wapi/getUserFullInfo?gids=2`，世界等级目前不知道哪里可以获取，但是可以通过游戏等级计算（除非降级）

**Comment by Jerry-FaGe** [comment]
> 原神游戏等级以及游戏昵称可以通过`https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn`获取，米游社头像`https://bbs-api.mihoyo.com/user/wapi/getUserFullInfo?gids=2`，世界等级目前不知道哪里可以获取，但是可以通过游戏等级计算（除非降级）

收到，不过如果只能通过cookie获取自己的话确实就无法整合到这个查询脚本里了😭

**Comment by Chika99** [comment]
我照着您的改改看，不过我觉得左上角放个派蒙也挺好看的hhh

**Comment by Womsxd** [comment]
> > 原神游戏等级以及游戏昵称可以通过`https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn`获取，米游社头像`https://bbs-api.mihoyo.com/user/wapi/getUserFullInfo?gids=2`，世界等级目前不知道哪里可以获取，但是可以通过游戏等级计算（除非降级）
> 
> 收到，不过如果只能通过cookie获取自己的话确实就无法整合到这个查询脚本里了😭

提供一个解决办法，但是要对面的米哈游的uid
https://bbs-api.mihoyo.com/game_record/card/api/getGameRecordCard?uid=米哈游账号uid

**Comment by Womsxd** [comment]
真要想获取的话建议逆向游戏，自己模拟游戏协议写一个客户端(

**Comment by Jerry-FaGe** [comment]
> 提供一个解决办法，但是要对面的米哈游的uid
> bbs-api:
> [https://bbs-api.mihoyo.com/game_record/card/api/getGameRecordCard?uid=米哈游账号uid](https://bbs-api.mihoyo.com/game_record/card/api/getGameRecordCard?uid=%E7%B1%B3%E5%93%88%E6%B8%B8%E8%B4%A6%E5%8F%B7uid)
> site-api:
> [https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=米哈游账号uid](https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=%E7%B1%B3%E5%93%88%E6%B8%B8%E8%B4%A6%E5%8F%B7uid)

emmm，貌似不太行，请问这个接口还需要请求头或者别的什么参数么

我用浏览器get请求

- https://bbs-api.mihoyo.com/game_record/card/api/getGameRecordCard?uid=18642672
```
{"data":null,"message":"invalid request","retcode":-10001}
```

- https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=18642672
```
{"data":null,"message":"invalid request","retcode":-10001}
```

`18642672` 是我的米哈游帐号 uid，换成原神uid `100131271` 也同样不行

**Comment by Womsxd** [comment]
> > 提供一个解决办法，但是要对面的米哈游的uid
> > bbs-api:
> > [https://bbs-api.mihoyo.com/game_record/card/api/getGameRecordCard?uid=米哈游账号uid](https://bbs-api.mihoyo.com/game_record/card/api/getGameRecordCard?uid=%E7%B1%B3%E5%93%88%E6%B8%B8%E8%B4%A6%E5%8F%B7uid)
> > site-api:
> > [https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=米哈游账号uid](https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=%E7%B1%B3%E5%93%88%E6%B8%B8%E8%B4%A6%E5%8F%B7uid)
> 
> emmm，貌似不太行，请问这个接口还需要请求头或者别的什么参数么
> 
> 我用浏览器get请求
> 
> * https://bbs-api.mihoyo.com/game_record/card/api/getGameRecordCard?uid=18642672
> 
> ```
> {"data":null,"message":"invalid request","retcode":-10001}
> ```
> 
> * https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=18642672
> 
> ```
> {"data":null,"message":"invalid request","retcode":-10001}
> ```
> 
> `18642672` 是我的米哈游帐号 uid，换成原神uid `100131271` 也同样不行

考虑也需要DS？
