### ISSUE TITLE
DS已失效

### ISSUE THREAD

**Issue by Chika99** [Womsxd/YuanShen_User_Info#18]
据米游社通知，app2.10及以下版本将无法使用游戏战绩功能

**Comment by Womsxd** [comment]
这。。我现在怀疑官方把ds的算法给更新了

**Comment by Mark9804** [comment]
如果DS算法改了的话应该所有的签到相关项目都会一起炸的，我这边测试genshinhelper和AutoMihoyoBBS还可以用
总之感觉先试试看把salt换成2.10试试看吧，如果还不行的话再怀疑DS
我最近在准备考试，暂时不跟进了

**Comment by Womsxd** [comment]
> 如果DS算法改了的话应该所有的签到相关项目都会一起炸的，我这边测试genshinhelper和AutoMihoyoBBS还可以用
> 总之感觉先试试看把salt换成2.10试试看吧，如果还不行的话再怀疑DS
> 我最近在准备考试，暂时不跟进了

这两个项目的DS基本上不会受到查询那边影响

**Comment by Android-KitKat** [comment]
可以看一下这边的两个讨论。

https://github.com/Arondight/Adachi-BOT/issues/51
https://github.com/Azure99/GenshinPlayerQuery/issues/20

**Comment by Mark9804** [comment]
看到了，那应该能坐实是DS的问题

我这边因为在忙，修bug的事情就拜托了.jpg

**Comment by Womsxd** [comment]
修好了！
