### ISSUE TITLE
问问那个post查询character详细信息的api怎么使用

### ISSUE THREAD

**Issue by scofieldle** [Womsxd/YuanShen_User_Info#20]
我传入的b按照讨论里面lulu佬的写法写好了，其他ds、md5算法以及header和url都和index 的写法一样的，传回的还是invallid requests，最好直接写一下可以参考[哈哈]

**Comment by xi-yue-233** [comment]
求一下post的character的写法+1

**Comment by Womsxd** [comment]
就把要post的json丢b里面，q留空

**Comment by xi-yue-233** [comment]
![QQ图片20210908103346](https://user-images.githubusercontent.com/58218656/132438042-e29ce101-c355-465d-961b-172d952dc5ff.png)
![QQ图片20210908103350](https://user-images.githubusercontent.com/58218656/132438060-6de4401b-1a20-43d8-a243-844b222b7f9c.png)
不是很懂，难道b不是应该和salt、n、i、r和q一起计算md5然后再跟i,r,c组合成一个数变成ds值吗

**Comment by Womsxd** [comment]
https://github.com/Azure99/GenshinPlayerQuery/issues/20#issuecomment-914989861

**Comment by scofieldle** [comment]
是传进去的body类型问题/
