### ISSUE TITLE
请问，这个可以实现对深境螺旋角色使用情况的爬取吗

### ISSUE THREAD

**Issue by c1608402582** [Womsxd/YuanShen_User_Info#3]
我尝试跟踪了变量的值，但是并没有找到有关深境螺旋角色使用情况及等级的属性（我太菜了，不会python）
现在我正在制作一个深境螺旋角色出场数据的排名，在使用大量样本的情况下进行分析，以此推断出最适合当前版本的角色，来使人可以更方便的可以抽取价值最高的卡池，而不是被一些片面的攻略带偏。
但是大量样本。。。。人力太难了.jpg，自己去米游社一个个看用了好长时间才统计了22个，还可能存在误差，不具有广泛代表性。可以的话，能请您更新一下或者指导一下我吗，，我的邮箱是ghs21468@gmail.com

**Comment by Womsxd** [comment]
深渊是另外一个API，因为我个人懒狗(世界5，深渊3-1 1⭐，为了记行)的属性，所以说就没写，如果有需要的话我可以提供API，但是需要你自己写解析

**Comment by Womsxd** [comment]
https://api-takumi.mihoyo.com/game_record/genshin/api/spiralAbyss?server=区服&role_id=UID&schedule_type=1

**Comment by Womsxd** [comment]
serverID可以看我源码这里

**Comment by c1608402582** [comment]
感谢。别人昨天教了教我，昨晚找到了这个接口，吐槽一下3个东西竟然用了3个接口……

**Comment by Womsxd** [comment]
> 感谢。别人昨天教了教我，昨晚找到了这个接口，吐槽一下3个东西竟然用了3个接口……

就只有这两个接口有用吧，其他的简单的看了下没什么用

**Comment by c1608402582** [comment]
另一个是tool接口，确实不知道有啥用，2333

**Comment by c1608402582** [comment]
> > 感谢。别人昨天教了教我，昨晚找到了这个接口，吐槽一下3个东西竟然用了3个接口……
> 
> 就只有这两个接口有用吧，其他的简单的看了下没什么用

另一个是tool接口，确实不知道有啥用，2333

**Comment by c1608402582** [comment]
> > 感谢。别人昨天教了教我，昨晚找到了这个接口，吐槽一下3个东西竟然用了3个接口……
> 
> 就只有这两个接口有用吧，其他的简单的看了下没什么用
https://api-takumi.mihoyo.com/game_record/genshin/api/character
今天又多了一个查看角色装备和命之座的功能，新功能+1

**Comment by Womsxd** [comment]
> > > 感谢。别人昨天教了教我，昨晚找到了这个接口，吐槽一下3个东西竟然用了3个接口……
> > 
> > 
> > 就只有这两个接口有用吧，其他的简单的看了下没什么用
> > https://api-takumi.mihoyo.com/game_record/genshin/api/character
> > 今天又多了一个查看角色装备和命之座的功能，新功能+1

只不过是post的，有丶可惜，而且好像可以实现查询单个角色的信息，新功能+1
争取明天把ID和角色的对应给搞好(
