### ISSUE TITLE
网页米游社无法登陆，它那个语序验证码怎么点都不对。切换过无痕和正常模式，也换过edge，chrome，360，firefox，ie等浏览器都点不对

### ISSUE THREAD

**Issue by SiNoWu** [Womsxd/YuanShen_User_Info#32]
![QQ图片20211231095208](https://user-images.githubusercontent.com/50437894/147800313-0ff7bbc3-90f3-4670-968b-453e6ea36a35.png)
![QQ图片20211231095352](https://user-images.githubusercontent.com/50437894/147800318-29120a35-fb81-4d30-a3eb-eeef92ce924a.png)
![1](https://user-images.githubusercontent.com/50437894/147800324-623d149b-f7f7-4937-8ce7-69de3e253c81.png)

我都怀疑我汉语有问题了

**Comment by Womsxd** [comment]
这，我怀疑是不是极验那边有问题，要不试试找米哈游那边？
