### ISSUE TITLE
新的角色圣遗物以及命座查询接口

### ISSUE THREAD

**Issue by huiyadanli** [Womsxd/YuanShen_User_Info#5]
POST  
```
https://api-takumi.mihoyo.com/game_record/genshin/api/character
```

请求内容样例：
```
{"character_ids":[10000034,10000025,10000005],"role_id":"100000000","server":"cn_gf01"}
```

---

顺带一提

```
https://api-takumi.mihoyo.com/game_record/genshin/api/index
```

新增了区域探索度和声望等级的返回。

**Comment by Womsxd** [comment]
声望返回已经更新更新进去了，然后B服目前也支持了，以及DS可能需要更新了

**Comment by Womsxd** [comment]
b服兼容是：在uid开头等于5的情况下server参数为cn_qd01

**Comment by Womsxd** [comment]
以及公不公开数据这个接口都能查询到XD
目前这个接口只有国外的4个服务器无法被查询到，国内的两个都能可以查

**Comment by huiyadanli** [comment]
> 声望返回已经更新更新进去了，然后B服目前也支持了，以及DS可能需要更新了

> b服兼容是：在uid开头等于5的情况下server参数为cn_qd01

DS 老的还能用，我也跟着你的代码更新到最新了，顺便支持了下B服

> 以及公不公开数据这个接口都能查询到XD
目前这个接口只有国外的4个服务器无法被查询到，国内的两个都能可以查

今天在云函数上集成并测试了下，的确又能够查到非公开的角色数据:joy:。。。
