### ISSUE TITLE
目前调用接口需要cookie了

### ISSUE THREAD

**Issue by Chika99** [Womsxd/YuanShen_User_Info#6]
然后隐藏战绩的似乎也查不到了

**Comment by Chika99** [comment]
不加入cookie提示需要登录，一部分账号可能是隐藏战绩的返回 {message: "Data is not public for the user", retcode: 10102}

**Comment by c1608402582** [comment]
怀疑加cookie的目的是限制请求次数。现在最多请求30次就会被限制，同时手机上也不能看别人的战绩了

**Comment by yimo0908** [comment]
米游社现在倒是可以随看玩家的战绩了

**Comment by Womsxd** [comment]
Cookie已经在首次运行的要求输入了（咕咕咕出来了）

**Comment by azhou125** [comment]
大佬Cookie要怎么获取呀
