### ISSUE TITLE
API报错

### ISSUE THREAD

**Issue by yukiryo** [Womsxd/YuanShen_User_Info#7]
`{"data":null,"message":"Please login","retcode":10001}`

**Comment by kernelbin** [comment]
添加你的cookies到headers即可。
cookies也很好抓，登录米游社（网页版即可）抓一下就行了

**Comment by Womsxd** [comment]
请自行添加cookie(

**Comment by KaikyuLotus** [comment]
I'm getting the same error,
does an account from www.hoyolab.com work or an account from bbs.mihoyo.com is needed?
