### ISSUE TITLE
[API ERROR] Invalid Request

### ISSUE THREAD

**Issue by kernelbin** [Womsxd/YuanShen_User_Info#8]
近日尝试调用API，在添加最新cookies（从米游社网页版抓取来的）之后仍得到返回结果：
```{"data":null,"message":"invalid request","retcode":-10001}```

怀疑可能是API进行了更新...?

**Comment by SleepyAsh0191** [comment]
DS算法已变，需要替换salt为pbcfcvnfsm5s2w4x3lsq8caor7v8nlqm，并修改app-version为2.4.0

**Comment by Chika99** [comment]
> 近日尝试调用API，在添加最新cookies（从米游社网页版抓取来的）之后仍得到返回结果：
> `{"data":null,"message":"invalid request","retcode":-10001}`
> 
> 怀疑可能是API进行了更新...?

用2.3.0的加盐方式可以

**Comment by Womsxd** [comment]
> > 近日尝试调用API，在添加最新cookies（从米游社网页版抓取来的）之后仍得到返回结果：
> > `{"data":null,"message":"invalid request","retcode":-10001}`
> > 怀疑可能是API进行了更新...?
> 
> 用2.3.0的加盐方式可以

2.3.0的加盐？最近一直在咕咕咕中(

**Comment by Womsxd** [comment]
马上更新2.4版本的盐

**Comment by Womsxd** [comment]
fix

**Comment by Womsxd** [comment]
@Chika99 是否可用？

**Comment by Chika99** [comment]
> @Chika99 是否可用？

2.3.0 和 2.4.0 的刚才试了下似乎都不可以了 明天再抓一下看看

**Comment by Womsxd** [comment]
> > @Chika99 是否可用？
> 
> 2.3.0 和 2.4.0 的刚才试了下似乎都不可以了 明天再抓一下看看

建议优先使用2.4，2.2.1到2.4才和谐，估计更新到2.5了2.3就和谐了吧

**Comment by Womsxd** [comment]
> > @Chika99 是否可用？
> 
> 2.3.0 和 2.4.0 的刚才试了下似乎都不可以了 明天再抓一下看看

你可以参考下我这边的header头，version要改成5了

**Comment by Chika99** [comment]
> > > @Chika99 是否可用？
> > 
> > 
> > 2.3.0 和 2.4.0 的刚才试了下似乎都不可以了 明天再抓一下看看
> 
> 你可以参考下我这边的header头，version要改成5了

哦，确实是x-rpc-client_type的问题，已经可用了
